### ISSUE TITLE
How do one prepare/uncompress the backup when there's no required qpress present?

### ISSUE THREAD

**Issue by pentago** [bitnami/bitnami-docker-mariadb#153]
**Description**

Backup creation/preparation/restoration suite isn't complete as **qpress** utility is missing from the image.

**Steps to reproduce the issue:**

1. Create compressed backup using `mariabackup --compress`
2. Attempt to prepare and decompress the backup with `mariabackup --prepare` and `mariabackup --compress`
3. Process breaks due to missing **qpress** utility as per screenshot above.

**Describe the results you received:**

Here's the proof: https://i.imgur.com/7uPGKdh.png

**Describe the results you expected:**

Successfully prepared and decompressed backup ready for applying.

**Version**

- Output of `docker version`:

```
Any
```

- Output of `docker info`:

```
Any
```

- Output of `docker-compose version` (if applicable):

```
Any
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
GKE

**Comment by andresbono** [comment]
Hi @pentago, did you use the following command to create the backup?

```
$ mariabackup --compress --target-dir /tmp/backup --backup --user root

$ mariabackup --decompress --target-dir=/tmp/backup
mariabackup based on MariaDB server 10.2.16-MariaDB Linux (x86_64)
180831 12:32:39 [01] decompressing ./ib_buffer_pool.qp
sh: 1: qpress: not found
cat: write error: Broken pipe
Error: thread 0 failed.
```

In that case, what you need to do is to install qpress. You can do it by adding the following commands in your mariadb Dockerfile, just make sure you add those lines before the `USER` instruction:

```
RUN curl http://www.quicklz.com/qpress-11-linux-x64.tar | tar x -C /usr/bin/
RUN chmod +x /usr/bin/qpress
```

Then, you need to rebuild the image and use it in your chart.

Let us know if it works for you.

-Andrés B.

**Comment by juan131** [comment]
Hi @pentago 

I agree with you. That package is needed in order to use the **mariabackup** utility. Therefore, it should be included by default on the image since it affects a core tool. 

I'll open an internal task to work on it and release a new version of MariaDB container including it asap. Thanks for reporting the issue.

**Comment by pentago** [comment]
Awesome, thanks!

**Comment by Fuseteam** [comment]
i was just wondering how backup and restores are made with the image

**Comment by juan131** [comment]
There's a task in our backlog to include **qpress** in the image by default so command such as `mariabackup --compress` properly work. I'd try to raise the priority of the task.

@Fuseteam to backup/restore data on this image you can use MariaDB own tools (such as mariabackup) or you can take a snapshot of the persistent volume mounted on MariaDB for the data. You can find more info in the link below:

- https://github.com/bitnami/bitnami-docker-mariadb#step-2-stop-and-backup-the-currently-running-container

**Comment by juan131** [comment]
What error did you find @Fuseteam ? Could you please share the exact command and errors you found in the logs?

**Comment by Fuseteam** [comment]
@juan131 i did not see an error, i did the rsync command from the readme. i had a particular test setup where i define the location of the volume in my home directory  like this: 
```
volumes:
 40   documentroot:
 41     driver: local
 42     driver_opts:
 43         type: none
 44         o: bind
 45         device: "${PWD}/www-data"
```
so i cd into the container folder and ran
`rsync -a www-data backup`
then i took the container down, removed the volume removed the custom path entered the rootshell with sudo su and ran
`rsync -a backup /var/lib/docker/volumes/container-folder_mariab`
and brought the container backup. but when checked my application i did not see my data, it was test data so no real data was lost.
i have in the meantime managed to make a new backup using the mariabackup tool to my home directory, looking forward to when qpress is in the image to give this backup/restore another go

**Comment by juan131** [comment]
Hi @Fuseteam 

I think I am missing something or I did not understand you correctly. Why are you backing up the `www-data` directory? Please note it's the MariaDB data directory the one I recommend you to backup. I mean the directory in your host that you are mounting at the `/bitnami/mariadb/data` directory inside the MariaDB container. Please check:

- https://github.com/bitnami/bitnami-docker-mariadb#upgrade-this-image

**Comment by Fuseteam** [comment]
because i had the docker compose set up to use www-data to be the location of volume of mariadb if i understood it correctly.
i had the container set up to using
```
volumes:
   - 'data:/bitnami'
```
and had the volume defined as:
```
volumes:
 40   data:
 41     driver: local
 42     driver_opts:
 43         type: none
 44         o: bind
 45         device: "${PWD}/www-data"
```

**Comment by Fuseteam** [comment]
btw `curl http://www.quicklz.com/qpress-11-linux-x64.tar` return a error 406

**Comment by juan131** [comment]
> unless i'm misunderstanding how this works

Okay, now I understand it. I was confused by the name since `www-data` is usually associated to web apps and you're using MariaDB.

So you backed up your data at `/var/lib/docker/volumes/container-folder_mariab`, and then you recreated the MariaDB container which is still using the `${PWD}/www-data` volume, right? I mean running the commands below:

```
$ docker-compose rm mariadb
$ docker run --name mariadb bitnami/mariadb:latest
```

> btw curl http://www.quicklz.com/qpress-11-linux-x64.tar return a error 406

It seems they're blocking connections when they detect there are certain missing headers in the HTTP request. This is usually done to avoid bots.

Try with:

```
curl -A "Mozilla/4.0" -L http://www.quicklz.com/qpress-11-linux-x64.tar | tar x -C /usr/bin/
```

**Comment by Fuseteam** [comment]
actually the other way around the container was using `${PWD}/www-data` so i backed up the data i thought was there and recreated the container without that folder with `docker-compose rm mariadb -v`

> It seems they're blocking connections when they detect there are certain missing headers in the HTTP request. This is usually done to avoid bots.

ah thanks for the tip

**Comment by juan131** [comment]
Hi @Fuseteam 

> actually the other way around the container was using `${PWD}/www-data` so i backed up the data i thought was there and recreated the container without that folder with `docker-compose rm mariadb -v`

So, were you able to reuse the existing data once you created again the MariaDB container?

> Note: the option `-v` removes "anonymous" volumes attached to containers. These volumes the ones that are not given an explicit name when they are first mounted into a container, so Docker gives them a random name that is guaranteed to be unique. See:
>
>```console
>$ docker-compose rm --help
>...
>Options:
>    -f, --force   Don't ask to confirm removal
>   -s, --stop    Stop the containers, if required, before removing
>    -v            Remove any anonymous volumes attached to containers
>```

**Comment by Fuseteam** [comment]
no for some reason i was not able to
rsync it into the volume at /var/lib, i have since manually recreated the data however; since it was test data

but for completeness it was a named volume that was suppose to be stored at a custom location( the www-data directory in my current directory) by using 
```
volumes:
 40   data:
 41     driver: local
 42     driver_opts:
 43         type: none
 44         o: bind
 45         device: "${PWD}/www-data"
```
the fact i have to repeat myself makes me wonder if the data was really stored there now.....

so i rsynced the data to another location, removed the volume as noted in the readme
changed the docker-compose to
```diff
volumes:
 40   data:
 41     driver: local
- 42     driver_opts:
- 43         type: none
- 44         o: bind
- 45         device: "${PWD}/www-data"
```
dropped to root shell rsynced the backuped data to the /var/lib/docker/volume path and brought the container back up
and the container did not seem to have the data

**Comment by juan131** [comment]
Hi @Fuseteam 

> so I rsynced the data to another location, removed the volume as noted in the readme

Could you please follow the instructions in the README.md without adding the `-v` flag? I mean, you use:

```
$ docker-compose rm mariadb
```

Instead of:

```
$ docker-compose rm -v mariadb
```

**Comment by Fuseteam** [comment]
did i misread? i'm positive i read the `-v` from the README

**Comment by juan131** [comment]
Yes, I'm suggesting to NOT follow the README.md, and avoid using the flag.

**Comment by Fuseteam** [comment]
ah i try that when i have a chance

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
