### ISSUE TITLE
vulnerabilities in bitnami/mariadb image, as detected by clair

### ISSUE THREAD

**Issue by anapsix** [bitnami/bitnami-docker-mariadb#159]
It appears, that latest `bitnami/mariadb` contains a number of undressed vulnerabilities, as detected by [Clair](https://github.com/coreos/clair); some more significant then other.

Please consider addressing those, and perhaps reflect on including vulnerability scans in docker image release process.

![clair_report_bitnami-mariadb](https://user-images.githubusercontent.com/1256199/45761570-2b448700-bc35-11e8-9df6-8c9f781928f7.png)
See details in JSON formatted Clair report [analysis-bitnami-mariadb-latest.json.txt](https://github.com/bitnami/bitnami-docker-mariadb/files/2397594/analysis-bitnami-mariadb-latest.json.txt)
```
$ docker images --digests bitnami/mariadb | column -t
REPOSITORY       TAG     DIGEST                                                                   IMAGE         ID  CREATED  SIZE
bitnami/mariadb  latest  sha256:afd5d0f1d98a533215df73ba0cbc1716d5ab79a788b2b8e73176eaeac976aa04  5e74cd384b6b  10  hours    ago   299MB
```

```
$ clairctl analyze --local bitnami/mariadb

Image: /bitnami/mariadb:latest

 Unknown: 4
 Negligible: 28
 Low: 10
 Medium: 14
 High: 10
 Critical: 0
 Defcon1: 0
```

P.S. Similar situation with `bitnami/postgresql`

**Comment by beltran-rubo** [comment]
Hi @anapsix Thanks for the detailed report and for your feedback.

Those are vulnerabilities in the distro packages that are not fixed by the distro itself. You can also check the following reports and click on "Show CVEs with fixes".

https://anchore.io/image/dockerhub/bitnami%2Fmariadb%3Alatest#security
https://anchore.io/image/dockerhub/bitnami%2Fpostgresql%3Alatest#security

Could you check in your report which of them have a fix already available?

We rebuild & release all our Bitnami catalog daily with all the latest versions. You can check all the tags created daily in dockerhub. E.g. MariaDB https://hub.docker.com/r/bitnami/mariadb/tags/  

You can also learn more about the daily releases policy and the rolling tags at  https://docs.bitnami.com/containers/how-to/understand-rolling-tags-containers/

I hope it helps.

**Comment by anapsix** [comment]
good point @beltran-rubo!
quick grok shows no fixes available for Debian 9 (Stretch) for of high severity vulnerabilities identified by Clair scan I've mentioned
too bad Anchore.io does not have a vulnerability status badge one could, similar to their "image overview"..

**Comment by javsalgar** [comment]
Thanks! We'll take a look and see if it makes sense to add it to our README pages :)
