### ISSUE TITLE
Question: Backup/Restore scripts

### ISSUE THREAD

**Issue by 4ydx** [bitnami/bitnami-docker-mariadb#171]
I am wondering if there would be any interest in trying to integrate backup/restore scripts?  Or would this be considered out of scope?

https://github.com/4ydx/debian-ubuntu-mariadb-backup

I have also looked at the helm chart bitnami makes available, but figured that any question I might ask there could get lost in the mix.

**Comment by javsalgar** [comment]
Thanks for the suggestion. It looks to me that backing up and restoring should be something done by a Kubernetes job, a sidecar container or an operator. 

Plus, I see that these scripts are tested and maintained for Debian or Ubuntu. However, the Bitnami MariaDB container offers other flavors like Oracle Linux or RedHat. Because of that, I wouldn't add these scripts to our container.

**Comment by javsalgar** [comment]
So, I think that, what it would make sense, would be trying to add a backup logic in the helm chart as cron jobs for examples. However, adding that's something we should discuss.

**Comment by 4ydx** [comment]
Is the recommendation then that scripts be made for files/docker-entrypoint-initdb.d that will automate the process of creating the backup user and preparing cron or do you mean to say that the kubernetes cronjob feature should be used?  I have to admit that I am new to kubernetes.

**Comment by Bessonov** [comment]
Just for a simple use case with mysqldump and mongodump I've created an example for s3: https://github.com/Bessonov/s3-backup

**Comment by javsalgar** [comment]
Cool, thanks for sharing! :)
