### ISSUE TITLE
Keep docker tag bitnami/mariadb:10 up to date

### ISSUE THREAD

**Issue by ddelange** [bitnami/bitnami-docker-mariadb#231]
**Description**

In my `bitnami/owncloud` docker-compose file, I would like to pin major versions only. For that, conveniently `bitnami/owncloud:10` points to latest (10.6.0 at the moment).

However, doing the same is not possible for `bitnami/mariadb:10` as it's not pointing to 10.5.8: https://hub.docker.com/r/bitnami/mariadb/tags?page=1&ordering=-name&name=10

Could CI be adjusted to update this tag?

**Comment by marcosbc** [comment]
Hi @ddelange, since there may be breaking changes between "minor" MariaDB versions (i.e. 10.3 -> 10.4) we are not supporting something like `mariadb:10`. Therefore, we consider "10.5" to be a MariaDB major and not just "10" as it is more stable for end users.

Note that it is also similar to how we do it with MySQL: https://github.com/bitnami/bitnami-docker-mysql

**Comment by ddelange** [comment]
Ah, that's good to know! Guess the plain `bitnami/mariadb:10` image in hub from 4 years ago just got me confused then.

In that case, it is probably also intentionally pinned for owncloud? With 10.5.8 everything seems to be working, so was surprised to see an outdated version in the compose:

https://github.com/bitnami/bitnami-docker-owncloud/blob/a5d944ba4991c4de0e7c860a7b65662af828f750/docker-compose.yml#L4

But as that's not strictly related to this repo, I'll close :)

Thanks! 💥

**Comment by marcosbc** [comment]
I see, you're right, for some assets we're still using previous MariaDB versions. We update it from time to time unless we find issues, which may have been the case for ownCloud and probably why we're still on 10.3.x.
