### ISSUE TITLE
Can we get ColumnStore support?

### ISSUE THREAD

**Issue by DreamwareDevelopment** [bitnami/bitnami-docker-mariadb#233]
I'm not sure how to modify this repo to get ColumnStore support given Bitnami's custom toolchain as seen in the Dockerfile, but if someone could point me in the right direction I'd be happy to fork it and make a PR. For now I'm using mariadb/columnstore docker image and have my own helm chart, but I'd rather not maintain my own helm chart as I'm a single developer working on an analytics application for fun.

**Comment by marcosbc** [comment]
Hi @DreamwareDevelopment, I'm not familiar with ColumnStore but I assume it would require to be compiled, right? Or does it only require changes to the Docker image and chart?

**Comment by DreamwareDevelopment** [comment]
@marcosbc Sorry for the delayed response. It can be installed as a plugin via apt-get. I tried pulling the bitnami image in a Dockerfile and then installing the plugin, but it seems that columnstore expects mysql to be in a different directory than /bitnami/mysql and I'm not sure how to tell it where to look for mysql data dir.

**Comment by marcosbc** [comment]
Hi @DreamwareDevelopment, apparently it would required to be enabled during compilation via the `-DPLUGIN_COLUMNSTORE=YES` flag.

For now, I've created an internal task for looking into this, but unfortunately I cannot give an ETA for when it would be completed.

**Comment by DreamwareDevelopment** [comment]
@marcosbc Thanks for looking into this. I'm having difficulties with my own helm chart and getting ColumnStore working. I think in the meantime I'll use the bitnami/mariadb chart and take the performance hit of using InnoDB and convert the analytics tables to use ColumnStore when it does eventually get supported. I don't have any data in the tables yet as I'm getting to MVP so it's better to just use what works for now and optimize later. If there's anything I can do to help please don't hesitate to ask.

**Comment by marcosbc** [comment]
Hi, I've taken a further look into what would be required and unfortunately it doesn't look feasible at the moment.

For now, compiling MariaDB with ColumnStore with `-DPLUGIN_COLUMNSTORE=YES` is more or less simple, only a few extra deps would be needed and the resulting image size would increase by about 50MB.

However, the ColumnStorage engine seems to require a lot of post-configuration which is not simple at all. Most importantly, the `post-install` script does not work in containers and would require lots of effort to adapt it properly, i.e.:

* By default it is integrated into systemd, without any option for using an alternative (note that systemd is not enabled by default in Bitnami containers)
* Some of the paths are hardcoded to use system paths (i.e. /usr or /var paths instead of /opt/bitnami/mariadb)
* It requires setting kernel settings, which for containers means forcing to set it at the host level

This is mentioned in the official [ColumnStore install guide](https://mariadb.com/kb/en/preparing-for-columnstore-installation-125/#initial-download-installation-of-mariadb-columnstore-binary-package).

I am going to leave this issue open for now, as well as the internal task, but unfortunately due to the above issues, I cannot guarantee that we will end up working on in the short-term or even long-term future.

**Comment by DreamwareDevelopment** [comment]
Hi, so from looking at the link you posted those are the install steps for ColumnStore 1.2.5, however the current version is 1.5. The folks over at mariadb have been working to reduce the installation friction and enabling its use in containers. You can see the code for mariadb's columnstore docker image here: https://github.com/mariadb-corporation/mariadb-community-columnstore-docker. The install process has been improved between 1.2.5 and 1.5, for instance running postConfigure is no longer needed after installation. Also, optimizing the kernel settings is no longer necessary. I'm not sure about the systemd issue you mentioned, but I imagine there should be a workaround, if not maybe I can open an issue on their repo. I'm also not sure how to workaround the hardcoded paths, perhaps creating symlinks is an option. Let me know what you think after taking a look at their image repo and the 1.5 install instructions here: https://mariadb.com/docs/deploy/enterprise-htap/#install-enterprise-columnstore-via-apt-debian-ubuntu

**Comment by marcosbc** [comment]
Thanks for sharing! I'll add that to the internal task. It seems like they created a separate Docker image just to include ColumnStore support, which is what we may need to do once we support it.

That said, it also looks like their Docker image is multi-process, which is a red flag at the moment. We usually only support multi-process containers for very specific things (like PHP web-apps with Cron, or web-apps with their own worker daemon).

I guess that it's something that they will eventually iterate on, at which point we may want to look into it. For now, it seems like support for that will have to wait until it gets more traction and we get more requests, like what happened with [MariaDB Galera](https://github.com/bitnami/bitnami-docker-mariadb-galera) or [MongoDB Sharded](https://github.com/bitnami/bitnami-docker-mongodb-sharded), for instance.

**Comment by Hoeze** [comment]
Are there any updates on this issue?

**Comment by carrodher** [comment]
Unfortunately, the internal task is still on our backlog, due to other priorities in the team and the capacity we have, we didn't find the bandwidth to start looking into this topic.

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
