### ISSUE TITLE
Outdated versions

### ISSUE THREAD

**Issue by FrederikNS** [bitnami/bitnami-docker-mariadb#24]
The current bitname/mariadb only goes to version 5.5. It would be nice if the 10.0 and the 10.1 versions was added to this docker image.

**Comment by prydonius** [comment]
Thanks for the suggestion @FrederikNS, it's on our roadmap and the 10.x versions should be released soon!

**Comment by hnq90** [comment]
:+1: for 10.x version

**Comment by hnq90** [comment]
@prydonius Hello,
How can I use the mariadb 10.0 or 10.1 in this docker image? Because [Spider](https://mariadb.com/kb/en/mariadb/spider/) is only available from MariaDB 10.0.4.

**Comment by chipironcin** [comment]
Hi @FrederikNS @hnq90 
We have already updated internally to MariaDB 10 series and now it is in the testing phase.
You may replace the version in the Dockerfile and the SHA256 in the installer.sha256 file but it won't work as MariaDB 10 has more requirements and missing libraries.

The new version will be available by the end of this month. Meanwhile, we will continue updating this repo with the latest MariaDB 5.x version available.

Thanks for your patience!

**Comment by hnq90** [comment]
@chipironcin Thank you for your response.
I understand that it takes time to work on MariaDB 10 but I think it could be better if you create a new branch for testing 10.x version.
This MariaDB docker image have pulled a lots (7.5K) so there're some people like me and @FrederikNS want to experiment that version too.

Btw, couldn't you pack MariaDB as executable file in next release? Instead of using another method to install it such as: `apt-get install mariadb`...etc. IMHO, it makes this project is more "open", easier to contribute :baby_chick: 

Thanks!

**Comment by prydonius** [comment]
Hi @hnq90,

It's currently not possible to create a branch for testing 10.x because we are in the midst of changing the underlying packaging system present in the base images. Once the changes in the base images have been made, we will be able to release 10.x, but until then we can only maintain the existing installers.

The Bitnami Docker images make use of Bitnami packages rather than the OS package manager; this helps us to ensure that our packages are self-contained, small and consistent across all our images. Additionally, it allows us to stay on top of security issues, and not have to rely on OS packages for security fixes.

We're sorry about the delay with this and really appreciate your patience, but rest assured we will release MariaDB 10.x within the next couple of weeks.

**Comment by hnq90** [comment]
@prydonius Yeah, I got it. 
Thank you :+1:

**Comment by prydonius** [comment]
Hey @FrederikNS / @hnq90 

We've just released our first version in the 10.x series: 10.1.13. The tag is live on Docker Hub now :) https://hub.docker.com/r/bitnami/mariadb/tags/.

Closing this out now, feel free to open another issue if you have anymore questions!

**Comment by hnq90** [comment]
@prydonius Yay. It's finally released. Thank you 👍
