### ISSUE TITLE
Memory consumption keeps growing

### ISSUE THREAD

**Issue by system1system2** [bitnami/bitnami-docker-mariadb#246]
I have a Bitnami WordPress stack with a MariaDB container (from this image) and a WordPress container (from this image: https://github.com/bitnami/bitnami-docker-wordpress) served by Docker 20.10.4 on Amazon Linux 2. 

These two containers serve a close-to-zero-traffic website (with a dozen visits per day, at best). Yet, in just 6 hours, their memory consumption went from 40% to 75% of the total available. **It never goes down, even with zero inbound traffic.**
And it keeps growing as we speak. At this pace, they'll have consumed all memory by end of the day.

I'm asking for help in this Issues board rather than the WP one mainly because MariaDB is the main offender, consuming memory faster than the WP container.

Notice that: 

- I'm using the very latest images for both containers 
- I launch them via docker-compose but, so far, I didn't apply and resource limitation rules to them.
- They communicate with each other via an internal Docker network and with the world through a Traefik edge router (which does not increase memory consumption at all)
- I'm using bind mounts for all 3 containers on the host

Questions:

1. Is this normal?
2. Should I use Deploy to limit memory? If yes, any recommendations?

Thanks

**Comment by yilmi** [comment]
Hi @system1system2,

I couldn't reproduce this issue on my end using the default docker-compose images or with the latest images. In none of the cases I tried my consumption increased (either messing around with the services or leaving it running).

Now, the issue you're seeing was also reported by WordPress community users which were not using Docker images. 

That's why I'd look at other things before looking at the image, none of our default configuration seem to change defaults that may affect memory consumption (see reference to MariaDB documentation).
For example, you could check:
- Wordpress installed plugins
- Wordpress possible changes to the default MariaDB configuration
- MariaDB configuration

There were a few memory leak fixed in the latests MariaDB 10.5.x releases, but as you use the latest image you should already have them.

If you can reproduce the issue without any of your specific configuration or plugins, let me know how you do it and I'll try to reproduce it again (how you start it, your extra flags, what are the exact values you use in your docker-compose.yml, rate at which the memory consumption increases, etc...).

Otherwise, you should look at the MariaDB logs (perhaps increasing the log level before) to understand what is exactly happening and also try to disable all the plugins you've installed and see if the behaviour persist, if not try reintroducing them one by one to identify the culprit.

Answering your questions so far:
- Is this normal? 
Not as far as I can tell
- Should I use Deploy to limit memory? If yes, any recommendations?
I would first try to understand why the consumption is increasing at such levels before setting limitations as these could lead to an out of memory error on MariaDB (which could still give you some interesting details though)

If you want to follow up on this, please provide more details (docker-compose.yml, extra config, MariaDB logs).

References:
- https://mariadb.com/kb/en/mariadb-memory-allocation/ (some troubleshooting steps and possible configurations)
- https://mariadb.com/kb/en/error-log/#configuring-the-error-log-verbosity (Increase log verbosity)
- You can find a few WordPress community issues related to the same problem

Thanks,
Yass

**Comment by system1system2** [comment]
Thanks a lot for the extended response, Yass. Further testing showed that the MariaDB container stabilizes at some points (significantly beyond initial expectation, probably due to some plugins, but still stable).
