### ISSUE TITLE
Mariadb Debian image CVE

### ISSUE THREAD

**Issue by Saikumarn78** [bitnami/bitnami-docker-mariadb#261]
Hi,

The images provided have the CVE OS vulnerabilities. I am attaching the list and hoping that would be taken care of in upcoming releases
[Mariadb Debian image CVE.xlsx](https://github.com/bitnami/bitnami-docker-mariadb/files/7809887/Mariadb.Debian.image.CVE.xlsx)
.

**Comment by carrodher** [comment]
Thanks for the detailed report. Those are vulnerabilities in the distro packages that are not fixed by the distro itself. You can also check the following report and click on "Only show fixable":
https://quay.io/repository/bitnami/mariadb?tab=tags

We rebuild & release all our Bitnami catalog daily with all the latest versions. You can check all the tags created daily in dockerhub. E.g. MariaDB https://hub.docker.com/r/bitnami/mariadb/tags/  

You can also learn more about the daily releases policy and the rolling tags at https://docs.bitnami.com/containers/how-to/understand-rolling-tags-containers and the CVE policy at https://docs.bitnami.com/kubernetes/open-cve-policy/

I hope it helps.

**Comment by Saikumarn78** [comment]
Hi @carrodher 
Does this mean getting those vulnerabilities fixes would happen once it is available in the Debian distro? However, I couldn't search on the report - maybe because of the access restrictions. 

Just wanted to know how to work around those vulnerabilities.

**Comment by carrodher** [comment]
The quay report is public, you shouldn't be logged to see the result. In the main view, you can click on the number of vulnerabilities for a specific tag to see the CVE scanner details.

We rebuild and release all the container images on a daily basis in order to bundle the latest version of the system packages available at that moment. So yes, if the package is fixed by the distro (Debian for this opensource catalog) it will be included in the next daily release

**Comment by mirekphd** [comment]
https://quay.io/organization/bitnami
```
 0 - 0 of 0
This namespace doesn't have any viewable repositories.
```

**Comment by mirekphd** [comment]
```
./ci/list-cve-in-latest-clair-report.sh bitnami/minideb:bullseye

Listing most important vulnerabilities in bitnami-minideb:bullseye-clair-cve-scan-20220617-142609.txt:

Unapproved vulnerabilities:
| [1;31mUnapproved[0m | Critical CVE-2022-1292      | openssl      | 1.1.1n-0+deb11u1 | The c_rehash script does not properly sanitise shell         |
| [1;31mUnapproved[0m | High CVE-2019-8457          | db5.3        | 5.3.28+dfsg1-0.8 | SQLite3 from 3.6.0 to and including 3.27.2 is                |

Defcon1 vulnerabilities:

Critical vulnerabilities:
| [1;31mUnapproved[0m | Critical CVE-2022-1292      | openssl      | 1.1.1n-0+deb11u1 | The c_rehash script does not properly sanitise shell         |

High vulnerabilities:
| [1;31mUnapproved[0m | High CVE-2019-8457          | db5.3        | 5.3.28+dfsg1-0.8 | SQLite3 from 3.6.0 to and including 3.27.2 is                |

```

**Comment by carrodher** [comment]
Hi, unfortunately, those security vulnerabilities are not fixed by the OS or the application itself, so although we built the images on a regular basis to provide the latest version of system packages, this kind of CVE will be reported while there is no new version patching the issue in the OS or the application.

The Bitnami Application Catalog (OpenSource) is based on Debian 11 but Bitnami, as part of VMware, provides a custom container and Helm Charts catalog based on the desired base image (generic distro such as Debian 10 & 11, CentOS 7, PhotonOS 3 & 4, Ubuntu 18.04 & 20.04, or custom golden image) through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).
